pygments: true
github: {
    "versions": {
        "jekyll": "1.5.1",
        "kramdown": "1.3.1",
        "liquid": "2.5.5",
        "maruku": "0.7.0",
        "rdiscount": "2.1.7",
        "redcarpet": "2.3.0",
        "RedCloth": "4.2.9",
        "jemoji": "0.1.0",
        "jekyll-mentions": "0.0.6",
        "jekyll-redirect-from": "0.3.1",
        "jekyll-sitemap": "0.2.0",
        "github-pages": "18",
        "ruby": "2.1.1"
    },
    "hostname": "github.com",
    "pages_hostname": "github.io",
    "api_url": "https://api.github.com",
    "environment": "dotcom",
    "public_repositories": [],
    "organization_members": [],
    "build_revision": "cbd866ebf142088896cbe71422b949de7f864bce",
    "project_title": "Patomic",
    "project_tagline": "A Datomic REST interface or PHP",
    "owner_name": "taywils",
    "owner_url": "https://github.com/taywils",
    "owner_gravatar_url": "https://github.com/taywils.png",
    "owner_homepage": "http://www.taywils.me",
    "repository_url": "https://github.com/taywils/patomic",
    "repository_nwo": "taywils/patomic",
    "repository_name": "patomic",
    "zip_url": "https://github.com/taywils/patomic/zipball/gh-pages",
    "tar_url": "https://github.com/taywils/patomic/tarball/gh-pages",
    "clone_url": "https://github.com/taywils/patomic.git",
    "releases_url": "https://github.com/taywils/patomic/releases",
    "issues_url": "https://github.com/taywils/patomic/issues",
    "wiki_url": "https://github.com/taywils/patomic/wiki",
    "language": "english",
    "is_user_page": false,
    "is_project_page": true,
    "show_downloads": true,
    "url": "http://taywils.github.io/patomic", 
    "contributors": []
}
